### ISSUE TITLE
Package array Error: Illegal pream-token (s): `c' used. ...=1.3]@{\,}s[table-unit-alignment = left]}

### ISSUE THREAD

**Issue by Kenlee217** [nuaatug/nuaathesis#106]
demo.tex中以下一段几处出现 Package array Error，如何解决？
\begin{tabular}
    {S[table-format=1.3]@{\,}s[table-unit-alignment = left]}
    \toprule
    \multicolumn{2}{c}{Heading} \\
    \midrule
    1.234 & \metre   \\
    0.835 & \candela \\
    4.23  & \joule\per\mole \\
    \bottomrule
  \end{tabular}
\end{table}
![Error](https://github.com/nuaatug/nuaathesis/assets/95963339/20894058-f42a-429c-b1ec-d5f4fe9da473)

**Comment by Nuaaqhm** [comment]
请问这个怎么解决呀
