### ISSUE TITLE
v1 貌似不支持跨列表格？

### ISSUE THREAD

**Issue by MonFig** [nuaatug/nuaathesis#12]
因为目前没有work on V2，而且马上交论文了，所以就先不看V2了😂

V1 貌似是不支持跨列表格的，需要自己在cls里加入`\RequirePackage{multicol} %% 跨列表格相关`

**Comment by MonFig** [comment]
// 其实我自己都不知道自己在哪个version上了

**Comment by JackWzh** [comment]
这种添加宏包就可以解决的 feature 其实并没必要开一个issue......模板主要解决的是封面制作、页眉页脚制作、文献应用格式订制、间距字体控制等所有人都必须面对且用Google无法直接解决的问题。我们虽然提供了一些公式、表格的示例代码，但是我们没办法面面俱到，抱歉......
