### ISSUE TITLE
摘要页标题间距过大

### ISSUE THREAD

**Issue by wkmyws** [nuaatug/nuaathesis#125]
![image](https://github.com/user-attachments/assets/d97f61e2-b277-4b2d-b282-2b0b06ec168d)
如图所示，中英两中摘要标题到正文的间距不一致，且中文摘要的间距明显要大一些

**Comment by TimoLin** [comment]
似乎是模板`cls`中的空白行引起的，不清楚是不是作者故意增大的`摘要`到`正文`间的距离，这个需要@yzwduck来看下。 
考虑到研究生院做的硕士/博士论文模板是坨💩，很多格式语焉不详，所以一些没明确说的格式我一般按自己的感觉来。

如果你觉得不美观，在`nuaathesis.cls`中找到下面的内容：
```tex
\newcommand\nuaa@make@abstract@master@cn{
  \ifnuaa@abstractopenright
    \cleardoublepage
  \else
    \clearpage
  \fi

  \chapter*{\heiti\nuaa@label@abstract}

  \begingroup
    \setlength\parindent{2\ccwd}
    \rmfamily\songti\indent

    \nuaa@abstract
  \endgroup
  \vskip 2\baselineskip minus 1.5\baselineskip

  \nuaa@put@kw{\nuaa@textbf{\songti\nuaa@label@keywords}}{\songti\nuaa@keywords}
}
```
看你想要什么效果，下面有两个方案：
## 效果1. 减小摘要到正文的间距
将`begingroup`中的空行删掉即可减小`摘要`到`正文`的间距，使其和英文页相同。
```tex
  \begingroup
    \setlength\parindent{2\ccwd}
    \rmfamily\songti\indent

    \nuaa@abstract
  \endgroup
```
## 效果2. 增大Abstract到正文的间距
对于英文Abstract页，则需要在`global.tex`中进行更改，在正文段前增加一个空行`~\\`：
```tex
\begin{abstractEn}
  ~\\
  This document introduces \nuaathesis, the \LaTeX{} document class for NUAA Thesis
```
