### ISSUE TITLE
本模板生成的PDF档在查重（PMLC）时可能会遇到障碍

### ISSUE THREAD

**Issue by Yohoa** [nuaatug/nuaathesis#15]
由本模板生成的PDF档在查重（PMLC）时可能会遇到障碍，查重时候可能需要和院方联系，通过提交文章的GBK编码的纯文本档进行查重。

我使用了本项目作为模板，搭配TexStudio (Mac) 编辑器用XeLaTeX编译著成了毕设论文。

但在学院组织PMLC（CNKI本科专用论文查重系统，但是找不到这个缩写的全拼）查重的时候，院方回报称我的论文「无法识别」；简单修改文本再次查重后，问题复现，看起来不是单次的孤立事件。

CNKI的查重除了支持pdf, doc, docx, wps 格式的文件之外，还支持GBK编码的、以txt为后缀名的纯文本的查重；因此，最后我将各个章节的tex文件拼接成一个txt文件，并从UTF-8转至GBK后请院方再次实验，方解决。

我猜测这与PDF档中文本（字符）层的编码有关系，但不明白具体之原因；我的论文在PDF Expert 中对任一段落文本的复制/编辑都会致使其变成乱码，检索功能也无法使用（尽管在TexStudio 中，PDF内容能够被检索）。
![2018-06-02 14 51 13](https://user-images.githubusercontent.com/17778268/40871756-7b860bb0-6674-11e8-9974-8e01d3c1d285.gif)

**Comment by yzwduck** [comment]
duplicate #11
tl;dr 制作模板时，没有测试文字的可复制性，给各位毕业生造成各种麻烦，在此表示非常抱歉。

谢谢你们能够信任这份模板，并用它来承载各位的毕业论文，也非常谢谢大家的各种问题反馈；
很遗憾的是模板作者（笔者）的能力有限，没能做出能让大家用得顺心的模板，在此表示诚挚的歉意，希望能够得到大家的谅解（如果可以的话，还请大家多多支持这份学位论文模板的发展）。

剧透：接下来可能会有两次大幅度更新；
前一次会解决乱码问题，完善模板文档，并添加英文/日文论文的支持（暑假开始前）；
后一次大概会重写参考文献的样式表，使其符合学校的要求（但愿暑假结束前能完成）。

**Comment by Yohoa** [comment]
感谢！
之前没有注意到这个问题与 #11 的重复。
