### ISSUE TITLE
4级标题的问题

### ISSUE THREAD

**Issue by lzyu** [nuaatug/nuaathesis#19]
\subsubsection{ xxxx }
最先显示出来的只有 xxxx ，
没有 比如 2.1.1.1的标题号。

**Comment by lzyu** [comment]
而且4级标题的字体 比 3级标题的字体还要大，。。。

**Comment by lzyu** [comment]
已经使用  \setcounter{tocdepth}{3}

**Comment by yzwduck** [comment]
谢谢反馈，已修正这个问题，已在模板里加上 `\setcounter{tocdepth}{3}`。
以为硕士和本科一样只允许三级标题，所以就没测试四级标题，结果是我看错了。

顺便一提，`1.1.1.1`在硕士的撰写要求里被叫做“三级标题”。
