### ISSUE TITLE
南航论文提交格式

### ISSUE THREAD

**Issue by stardomlee** [nuaatug/nuaathesis#25]
感谢LaTeX模版。
我们学校提交论文的时候，最后的PDF文稿可以吗？我看同学全是word版，就怕latex写到最后学校非要word就麻烦啦

**Comment by yzwduck** [comment]
据几位前辈说，本科也可以交 PDF 格式的论文。

**Comment by stardomlee** [comment]
好的，感谢回复！

**Comment by yzwduck** [comment]
补充一下，亲测硕士可以全程提交 PDF（包括盲审、查重、图书馆），部分场景（图书馆）只接受 PDF。
但在印刷厂打印时，推荐额外准备一份 Word 版的封面（就第一页），因为 ta 们 *花钱* 定制了 Word 宏来生成最终打印用的封面，还用到了一些方正版权字体；还要记得修改论文的文档类参数 `oneside` -> `twoside`。
博士应该和硕士一样，但我不知道是否有人测试过。
