### ISSUE TITLE
博士论文模版页眉位置以及次级标题英文字体问题咨询

### ISSUE THREAD

**Issue by stardomlee** [nuaatug/nuaathesis#27]
Nuaa论文LaTeX模版开发者：
很感谢分享这么棒的写作模版。我这几天写博士论文有个问题想咨询下：
1）我对比了一下之前毕业同学的博士论文打印的word版本，然后用我的写的latex排版格式进行了比对，发现基于latex模版打印出来的页眉位置相比word模版的整体偏下。我附带了图片，尝试看了一下编译代码，但没有解决，因此想来咨询一下；
![IMG_8856](https://user-images.githubusercontent.com/23466046/57965690-1feb5c00-797a-11e9-8c56-b712acd2ddc9.JPG)

2）关于次级标题英文字体：
从目前的排版格式，英文的标题字体以及正文部分英文单词字体是Times New Roman没有多大问题，但是章节大标题以及次级标题等部分英文单词的字体似乎不是Times New Roman，而是其他的如黑体一样的字体，如
<img width="423" alt="image" src="https://user-images.githubusercontent.com/23466046/57965767-0696df80-797b-11e9-9e20-b35481716145.png">

<img width="386" alt="image" src="https://user-images.githubusercontent.com/23466046/57965774-1e6e6380-797b-11e9-8d0e-479a67704911.png">

这个应该如何解决呢？方便的话请告知一下。
非常感谢！

**Comment by yzwduck** [comment]
请在 `global.tex` 里 **添加** 代码，以覆盖模板指定的参数。

1）学校的撰写要求说，页面设置：上下 3.3cm，你的图中，LaTeX 的上页边距空白大概 4.5cm，Word 的大概 1.5cm，如果页边距的设置都正确的话，应该优先检查打印机是否有问题。如果要修改代码的话：
```latex
\geometry{
	top=3.3cm, bottom=3.3cm, left=3.0cm, right=2.8cm,
	headheight=15.6bp, headsep=0.15cm, footskip=15.6bp
}
```
2）我认为英文全文用衬线字体/Times New Roman 违背了中英文字体统一的原则，如果要修改各级标题字体的话：
```latex
\makeatletter
\renewcommand\nuaa@font@title{\heiti}
\makeatother
```

**Comment by stardomlee** [comment]
@yzwduck 非常感谢回复！第二个问题通过添加您给的代码，已经解决次级标题中的英文字体问题。

关于研究生论文中页眉页脚的问题，学校要求页眉：2.6 （cm）  页脚：2.6（cm），参照tex的模版pdf是在 fancyhdr 来设置，我想问下符合这个要求吗？或者如果自己修改参数的话，是在哪个宏文件中找到相关的命令行？

非常感谢！

**Comment by yzwduck** [comment]
就是要用到上面的 `geometry` 命令，而不是用 `fancyhdr`。
学校规定的页眉 2.6cm **貌似** 是指从纸张顶部到页眉顶部的距离，LaTeX 的 geometry 宏包不支持这种参数，需要换算成页眉的高度（一行文字，高度固定为 15.6bp=15.6/72 inch）和页眉与正文距离（计算 3.3cm-2.6cm-15.6bp≈0.15cm），参数的含义请看 [geometry 文档的 Figure 2](http://mirrors.ctan.org/macros/latex/contrib/geometry/geometry.pdf)。

---
需要注意的是，学校的撰写说明（模板），只有摘要到缩略词的 6 页的页眉设置是正确的，后面 5 页都是错的（实际为 Word 默认配置），请不要找错参照目标。
