### ISSUE TITLE
使用 nuaathesis 完成本科毕设的经验小结

### ISSUE THREAD

**Issue by infancy** [nuaatug/nuaathesis#28]
## 使用原因

* 毕设里会用到比较多的数学公式
* 不想手动排版、管理参考文献

## 工作流程

1. 准备工作：阅读相关资料。
2. 开发环境：TexLive 2018（编译器） + VS Code（编辑器） + LaTex WorkShop（VS Code 的 LaTex 插件）+mathpix（数学公式OCR）。
3. 工作过程：按需修改 demo_chs/bachelor.tex 和 demo_chs/content 下的内容，LaTex WorkShop 会自动编译，但是如果用了 BibTex 生成参考文献，需要手动选 xelatex -> bibtex -> xelatex*2 的方式编译（编译时长会大幅增加，而且很容易出编译错误的样子）。

![QQ截图20190606230537](https://user-images.githubusercontent.com/16622802/59043880-a4f9cf00-88af-11e9-9c28-91dea8ed9a7d.png)

## 导师审阅、查重、格式

1. 导师审阅：在使用 LaTex 写毕设前记得和导师沟通一下，因为大部分同学应该是发 word 文档给老师检查的，用了 LaTex 就得发 pdf 过去了。
2. 查重：学校应该是用 PMLC 系统查重的，我使用 UTF-8 字符集生成的 pdf 在查重时没有碰到问题，这和 #15 描述的不太一样。
3. 格式：nuaathesis 的本科论文段落统一缩进了2个字符，但班上的几位同学提醒我不需要这个操作。我按他们说的做了修改，最后答辩时没有遇到老师在格式上提的问题。

## 总结

1. 写论文的时候不用管一堆琐碎的问题，基本专注在内容上。
2. 班上应该至少有四位同学用了本模板做毕设。

##

最后感谢各位学长学姐制作的这份模板，祝 nuaathesis 的 ⭐  、🍴 越来越多！

**Comment by yzwduck** [comment]
因 AutoFakeBold 导致文本乱码，已经发布了一个禁用 AutoFakeBold 的版本，但是部分需要粗体的地方没有修正好，所以对应的 issue 没有关掉。

正文左侧缩进 2 字符的要求被去掉了吗？

**Comment by infancy** [comment]
学校给的模板是有缩进的，但有的同学专门被老师要求不需要缩进，这就有点混乱了（摊手）。

**Comment by yzwduck** [comment]
那就暂时不去改动吧，谢谢你的经验分享。
