### ISSUE TITLE
中文论文中夹杂少量日语显示出错

### ISSUE THREAD

**Issue by stardomlee** [nuaatug/nuaathesis#29]
大家好：
有个问题想再次请教一下，我的中文论文中需要加少量日语，利用XeLaTeX编译成功后，发现日语有几处显示是错的，应该是字体等原因。找了一下原因，但还是不对，请问一下如何解决？
非常感谢！
<img width="696" alt="image" src="https://user-images.githubusercontent.com/23466046/59236344-57bb8b80-8c28-11e9-9dc5-d613be881ab2.png">

**Comment by yzwduck** [comment]
从你的截图中可以看出“核融”和“議”是中文字体；如需使用日文字体，要做一些额外的设置：
1. 在 `global.tex` 里，取消 `\setCJKfamilyfont{mc}` 和 `\setCJKfamilyfont{gt}` 的注释（将上方的 `\iffalse` 改为 `\iftrue`），并根据操作系统，指定日文字体；
2. 在正文中需要日文字体的地方，使用 `\jpn{}` 进行标注，如 `\jpn{第２回レーザー核融合戦略会議}`

**Comment by stardomlee** [comment]
@yzwduck 非常感谢您及时的回复！按照建议，我尝试修改了一下，可能是我Mac中日语字体的问题，默认的修改出现编译错误。网上找了一下修改的方法，还是有问题。请问有什么容易的方法进行修改吗？
![image](https://user-images.githubusercontent.com/23466046/59329027-713ffe80-8d20-11e9-8987-158244ed26d1.png)

**Comment by yzwduck** [comment]
macOS 可以用系统自带的ヒラギノ字体，具体的代码如：
```latex
\iftrue
  \setCJKfamilyfont{mc}[BoldFont=HiraMinProN-W6]{HiraMinProN-W3}
  \newcommand\mcfamily{\CJKfamily{mc}}
  \setCJKfamilyfont{gt}[BoldFont=HiraginoSans-W6]{HiraginoSans-W3}
  \newcommand\gtfamily{\CJKfamily{gt}}
\fi
```
奇怪的是，我在 macOS 上用默认的中文字体 (STSongti-SC-Light) 没出现乱码…是你的 mac 还是 TeXLive 版本问题吗？
![Screen Shot 2019-06-12 at 18 49 24](https://user-images.githubusercontent.com/3306201/59345600-0522c200-8d43-11e9-8fcd-7c6cf742dee2.png)

**Comment by stardomlee** [comment]
@yzwduck 非常感谢！
现在显示正常了，我也觉得很奇怪。最开始编译的时候，也是没有更改global.tex里面的全局变量，日语显示是正常的，但是最近一段时间就显示出现问题了。不知道是不是更新引起的问题？
我的电脑编译环境是：macOS 10.15 Beta + TexShop4.27。

**Comment by yzwduck** [comment]
这有点难 debug，我很少用 macOS，没有感觉到这问题。
题外话：建议检查一下 PDF 输出，特别是“核融”和“議”这三个字，字形应该和我截图中的上一行一致；如果和下面那行的相似的话，就意味着错用中文字体了。

**Comment by stardomlee** [comment]
@yzwduck 
仔细比对了刚刚您提供给我的截图，我把我刚才编译的也发过来了，

**Comment by stardomlee** [comment]
@yzwduck 非常感谢回复。
仔细比对了刚刚您提供给我的截图，我把我刚才编译的也发过来了，感觉是对的。按照您刚才的建议，中文字体错误的话，我不是很懂。我用的是本网站默认的中文论文模版格式，没有更改过，只是修改过\geometry{}等的设置。不知道为什么会出现这个问题。

<img width="802" alt="image" src="https://user-images.githubusercontent.com/23466046/59350459-afecad80-8d4e-11e9-93ce-de5ee5394ca3.png">

**Comment by yzwduck** [comment]
是我没把话说清楚：中/日文字体字形有别，我的截图中的第一行是用了日文字体，第二行用的是中文字体。**如果** 日文的 PDF 输出结果和第二行相似，就表明用错字体了。
你的中文/日文字体设置没有问题。

**Comment by stardomlee** [comment]
@yzwduck 嗯嗯 谢谢解答。
