### ISSUE TITLE
论文题目强制换行显示

### ISSUE THREAD

**Issue by stardomlee** [nuaatug/nuaathesis#30]
各位，请教一个问题，在latex论文`global.tex`中的`title={}`中，我想要在某个固定的字后面换行显示题目，怎么做呢？因为我的论文题目比较长。
比如`title={我是谁}`我想要让谁在pdf中显示在第二行，我是显示在第一行。

谢谢。

**Comment by yzwduck** [comment]
这样的写法能满足你的需求吗？
https://github.com/nuaatug/nuaathesis/blob/1cd23bc9b9efd6c98426a9c8f83e76b349b301f9/demo_chs/global.tex#L22

**Comment by stardomlee** [comment]
@yzwduck 谢谢你的解答，已经可以强制换行了使用\linebreak。我还问一下我的论文题目中有一个英文字母，但是默认的字体是黑体，能不能让英文变成新罗马呢？只针对论文大标题。

非常感谢

**Comment by yzwduck** [comment]
1. 如果只改封面：
```latex
title = {\nuaathesis{} 快速上手\linebreak 示例 \rmfamily{document}},
```

2. 如需改所有标题：参见 #27 里的问题 (2)。

**Comment by stardomlee** [comment]
@yzwduck 谢谢回复。按照您的意见，我设置了一下title，字母变成了新罗马，但是字母后面的中文不再是加粗的了，这是为什么呢？麻烦了
`  title = {。。。。体\rmfamily{X}射线源。。。},`
![图片](https://user-images.githubusercontent.com/23466046/67494963-b26ff400-f6ac-11e9-9bc0-8d0fbc623f35.png)

**Comment by yzwduck** [comment]
失误了，我以为 `\rmfamily` 不会影响后面的样式。但事实上它会，那就这么写：
```latex
title = {\nuaathesis{} 快速上手\linebreak 示例 {\rmfamily{document}} 文档}
```

**Comment by stardomlee** [comment]
@yzwduck 完美解决疑惑，非常感谢！
