### ISSUE TITLE
算法伪代码缩进问题

### ISSUE THREAD

**Issue by Ji-Peng** [nuaatug/nuaathesis#36]
算法伪代码的缩进很奇怪。
![image](https://user-images.githubusercontent.com/57220004/80557133-7d9c7b00-8a08-11ea-98b8-200124ba3082.png)
请问如何修复呢？

**Comment by yzwduck** [comment]
我不太清楚你用模板和参数，没能复现出问题。能否贴上 MWE (minimal working example) 以方便调查问题？

**Comment by Ji-Peng** [comment]
使用demo_en模板，在demo_en文件夹下，编译bachelor_jp.tex即可得到下图。我希望算法伪代码能够和自然段对齐。我添加了附件 .zip 十分感谢
![image](https://user-images.githubusercontent.com/57220004/80586628-cc1d3a00-8a47-11ea-8035-643c04e60e7c.png)
[nuaathesis _debug.zip](https://github.com/nuaatug/nuaathesis/files/4551146/nuaathesis._debug.zip)

**Comment by yzwduck** [comment]
Word 里的插图会继承正文的样式（本科要求段落整体缩进 2 字符），它的插图能与正文对齐。
LaTeX 的插图/表格/算法是 float 环境，它有独立的样式，与上下文无关。目前没找到设置 float 环境统一缩进 2 字符的方法，所以很抱歉，本科模板里的插图没能与正文对齐。

**Comment by Ji-Peng** [comment]
好的，十分感谢您的耐心回答
