### ISSUE TITLE
请问一下如何将表中的英文修改为中文的形式？

### ISSUE THREAD

**Issue by 40m41h42t** [nuaatug/nuaathesis#38]
我使用了 `listings` 这个包，然后按照这个格式插入了一串代码：

``` tex
\begin{lstlisting}[caption={不透明谓词示例一}, label={tab:opaque1}, frame=single]
xxxxxx
\end{lstlisting}
```

编译后生成的是这个格式：

![Snipaste_2020-05-16_19-16-54](https://user-images.githubusercontent.com/43204230/82118427-f5f59100-97a9-11ea-95d9-d463d7e07112.png)

我希望将其中的 `Listing` 改为中文该怎么做呢？

**Comment by 40m41h42t** [comment]
另外好像不管怎么设置 `label` 都不会被 `\autoref` 引用

**Comment by yzwduck** [comment]
目前模板没有适配常用宏包（偷懒的借口），你可以在 global.tex 里加上：
```
\renewcommand{\lstlistingname}{演算法}
\newcommand\lstlistingautorefname{算法}
```
当然，上面的名字只是示例，请根据自己的需求，修改成合适的名字。

**Comment by 40m41h42t** [comment]
非常感谢！
