### ISSUE TITLE
关于VScode编译bib报错的问题

### ISSUE THREAD

**Issue by DragonOnGit** [nuaatug/nuaathesis#43]
下载模板以后，设置了latex的一些编译选项：
`
        // ======================== LaTeX 设置 BEGIN  ========================
        // bibtex 格式
        "latex-workshop.bibtex-format.tab": "tab",
    
        // 自动编译，全部关闭，当且仅当你认为有需要的时候才会去做编译
        "latex-workshop.latex.autoBuild.run": "never",
        "latex-workshop.latex.autoBuild.cleanAndRetry.enabled": false,
    
        // 设置 latex-workshop 的 PDF　预览程序，external　指的是外部程序
        "latex-workshop.view.pdf.viewer": "external",
        "latex-workshop.view.pdf.ref.viewer": "external",
        "latex-workshop.view.pdf.external.viewer.command": "C:/Program Files (x86)/SumatraPDF/SumatraPDF.exe",
        "latex-workshop.view.pdf.external.viewer.args": [
            "%PDF%"
        ],
    
        // 配置正向、反向搜索：.tex -> .pdf
        "latex-workshop.view.pdf.external.synctex.command": "C:/Program Files (x86)/SumatraPDF/SumatraPDF.exe",
        "latex-workshop.view.pdf.external.synctex.args": [
            // 正向搜索
            "-forward-search",
            "%TEX%",
            "%LINE%",
            "-reuse-instance",
            // 反向搜索
            "-inverse-search",
            "\"D:/Software/Microsoft VS Code/Code.exe\" \"D:/Software/Microsoft VS Code/resources/app/out/cli.js\" -gr %f:%l",
            "%PDF%"
        ],
    
        // 这是一些独立的编译选项，可以作为工具被编译方案调用
        "latex-workshop.latex.tools": [
            {
                // Windows 原生安装 TeX Live 2020 的编译选项
                "name": "Windows XeLaTeX",
                "command": "xelatex",
                "args": [
                    "-synctex=1",
                    "-interaction=nonstopmode",
                    "-file-line-error",
                    "-pdf",
                    "%DOCFILE%"
                ]
            },
            {
                // Windows Biber 编译
                "name": "Windows Biber",
                "command": "biber",
                "args": [
                    "%DOCFILE%"
                ]
            },
            {
                // WSL XeLaTeX 编译一般的含有中文字符的文档
                "name": "WSL XeLaTeX",
                "command": "wsl",
                "args": [
                    "/usr/local/texlive/2020/bin/x86_64-linux/xelatex",
                    "-synctex=1",
                    "-interaction=nonstopmode",
                    "-file-line-error",
                    "-pdf",
                    //"-output-directory=%OUTDIR%",
                    //"-aux-directory=%OUTDIR%",
                    "%DOCFILE%"
                ]
            },
            {
                // WSL biber / bibtex 编译带有 citation 标记项目的文档
                "name": "WSL Biber",
                "command": "wsl",
                "args": [
                    "/usr/local/texlive/2020/bin/x86_64-linux/biber",
                    "%DOCFILE%"
                ]
            }
        ],
    
        // 这是一些编译方案，会出现在 GUI 菜单里
        "latex-workshop.latex.recipes": [
            {
                // 1.1 Windows 编译简单的小文档，这个选项不太常用，因为绝大多数文章都需要有参考文献索引
                "name": "Windows XeLaTeX 简单编译",
                "tools": [
                    "Windows XeLaTeX"
                ]
            },
            {
                // 1.2 Windows 编译带有索引的论文，需要进行四次编译；-> 符号只是一种标记而已，没有程序上的意义
                "name": "Windows xe->bib->xe->xe 复杂编译",
                "tools": [
                    "Windows XeLaTeX",
                    "Windows Biber",
                    "Windows XeLaTeX",
                    "Windows XeLaTeX"
                ]
            },
            {
                // 2.1  WSL 编译简单的小文档，这个选项不太常用，因为我绝大多数文章都需要有引用。
                "name": "XeLaTeX 简单编译",
                "tools": [
                    "WSL XeLaTeX"
                ]
            },
            {
                // 2.2 带有 citation 索引的文档，需要进行四次编译；-> 符号只是一种标记而已，没有程序上的意义
                "name": "xe->bib->xe->xe 复杂编译",
                "tools": [
                    "WSL XeLaTeX",
                    "WSL Biber",
                    "WSL XeLaTeX",
                    "WSL XeLaTeX"
                ]
            }
        ],
    
        // 清空中间文件
        "latex-workshop.latex.clean.fileTypes": [
            "*.aux",
            "*.bbl",
            "*.blg",
            "*.idx",
            "*.ind",
            "*.lof",
            "*.lot",
            "*.out",
            "*.toc",
            "*.acn",
            "*.acr",
            "*.alg",
            "*.glg",
            "*.glo",
            "*.gls",
            "*.ist",
            "*.fls",
            "*.log",
            "*.fdb_latexmk",
            "*.bcf",
            "*.run.xml",
            "*.synctex.gz"
        ]
    // ======================== LaTeX 设置 END ========================
}
`

然后使用这里面的复杂编译即编译四次的时候，在最后一次编译会报错：

`
INFO - This is Biber 2.14
INFO - Logfile is 'master.blg'
ERROR - Cannot find 'master.bcf'!
INFO - ERRORS: 1
`
模板文件里面好像是没有这个文件的，请问这是bug还是我设置的有问题？

**Comment by CaralHsi** [comment]
同学请问你解决了吗

**Comment by yzwduck** [comment]
Hi @CaralHsi 我觉得大概是环境配置的问题，能否提供一份“最小样例”（和配置文件）来方便我们调查问题？

**Comment by CaralHsi** [comment]
> Hi @CaralHsi 我觉得大概是环境配置的问题，能否提供一份“最小样例”（和配置文件）来方便我们调查问题？

抱歉，后来这个问题自动消失了，我并未保存之前有问题的版本。如果该问题再次出现，我会在此回复。谢谢~

**Comment by DragonOnGit** [comment]
> Hi @CaralHsi 我觉得大概是环境配置的问题，能否提供一份“最小样例”（和配置文件）来方便我们调查问题？

我这边后来重新写了这个四次编译的文件
`
// 这是一些独立的编译选项，可以作为工具被编译方案调用
        "latex-workshop.latex.tools": [
            {
                // Windows 原生安装 TeX Live 2020 的编译选项
                "name": "Windows XeLaTeX",
                "command": "xelatex",
                "args": [
                    "-synctex=1",
                    "-interaction=nonstopmode",
                    "-file-line-error",
                    "-pdf",
                    "%DOCFILE%"
                ]
            },
            {
                // Windows Biber 编译
                "name": "Windows Biber",
                "command": "biber",
                "args": [
                    "%DOCFILE%"
                ]
            },
            {
                // 使用NUAA模板中推荐的方法编译
                "name": "NUAALaTeX",
                "command": "latexmk",
                "args": [
                    "-xelatex",
                    "%DOCFILE%"
                ]
            }
        ],
    
        // 这是一些编译方案，会出现在 GUI 菜单里
        "latex-workshop.latex.recipes": [
            {
                // 1.1 Windows 编译简单的小文档，这个选项不太常用，因为绝大多数文章都需要有参考文献索引
                "name": "单次编译-XeLaTeX",
                "tools": [
                    "Windows XeLaTeX"
                ]
            },
            {
                // 1.2 Windows 编译带有索引的论文，需要进行四次编译；-> 符号只是一种标记而已，没有程序上的意义
                "name": "四次编译--xe->bib->xe->xe",
                "tools": [
                    "Windows XeLaTeX",
                    "Windows Biber",
                    "Windows XeLaTeX",
                    "Windows XeLaTeX"
                ]
            },
            {
                // 2 使用NUAA中推荐的编译方法
                "name": "NUAALaTeX",
                "tools": [
                    "NUAALaTeX"
                ]
            }
        ],
`
现在这个编译问题解决了
