### ISSUE TITLE
在overleaf 上的编译问题

### ISSUE THREAD

**Issue by sunzhon** [nuaatug/nuaathesis#44]
在overleaf 上编译时 遇到编译器报错如下：
 
LaTeX Error: This file needs format `pLaTeX2e'  but this is `LaTeX2e'.

**Comment by yzwduck** [comment]
因为我不是 overleaf 的用户，所以不清楚在这个平台上的具体使用方法。
从错误信息来看，你大概使用了日文的语言选项，它需要 upLaTeX 才能编译。
请检查一下打开的主文件是否符合你的预期，找一下 overleaf 上面是否能修改编译流程（推荐使用 latexmk，如果需要手工指定，一般选择用 XeLaTeX）。

**Comment by sunzhon** [comment]
Thnaks. Yes, I think you are right. By just loading demo_chs in overleaf, and compile, it works well.
