### ISSUE TITLE
关于证明环境的跨页问题。

### ISSUE THREAD

**Issue by huxinwen1994** [nuaatug/nuaathesis#49]
我在附录中写证明时，使用了\begin{proof}..\end{proof}，但是proof不能跨页（如图所示，超出52行的部分不显示在第二页中），请问能否解决呀？
![捕获](https://user-images.githubusercontent.com/48075456/103399342-a10d5c00-4b7b-11eb-87a5-ddc6026a8b34.PNG)

**Comment by yzwduck** [comment]
你好，从贴图来看，这份文档没有使用 nuaathesis 文档类，  我也没能复现你遇到的问题。能否提供一份复现问题的最小代码 (MWE)，这样我才有研究问题的方向。

顺便，我是用的 MWE 是这样的：
```latex
\documentclass{ctexbook}
\usepackage{amsthm}
\usepackage{lipsum}
\begin{document}

\chapter{正文}

内容

\appendix

\chapter{附录章}

\begin{proof}
复杂的证明。

\lipsum[1-10]
\end{proof}

\end{document}
```

**Comment by huxinwen1994** [comment]
我知道问题在哪了，我加了一个package  \usepackage{oz}用于写一些Z notation。加了这个包会导致我上面所说的问题，你可以试一试呢？

**Comment by yzwduck** [comment]
引入 oz 后，确实复现了你提到的问题。
这个包可能由于过于小众、缺少维护等原因，已经无法与 ctex 共存。
我觉得可以试试其他的宏包，比如 zed-csp（它貌似与 siunitx 不兼容）。

**Comment by huxinwen1994** [comment]
非常感谢，似乎只有oz package能编写我的z notation。我的解决办法是：将nuaathesis.cls中的proof名字改为proofs，然后在正文中使用用\begin{proofs}...\end{proofs}，看上去还不错~
