### ISSUE TITLE
公式编号问题

### ISSUE THREAD

**Issue by HjsGithub95** [nuaatug/nuaathesis#50]
我导师在检查我论文的时候说要我给文中的公式编号加上括号，和公式右侧编号统一格式，请问这个在模板里怎么修改呢
![QQ截图20210105154558](https://user-images.githubusercontent.com/44230268/103619843-66396880-4f6d-11eb-8676-6cc7d64a5907.png)

**Comment by yzwduck** [comment]
`\autoref` 只能在 `\ref` 加上前缀，无法加上后缀。我目前只想到手工修改正文中对公式的引用：
1、像《示例文档》那样，每处引用都写成 `式~(\ref{equ:2})`（上面的第一句话也是从示例文档里摘录的）；
2、或者在 global.tex 里定义一个宏 `\newcommand\equref[1]{式~(\ref{#1})}`，然后正文中统一使用 `\equref`；
3、试试这个问题里提到的方法 https://tex.stackexchange.com/q/191376

**Comment by HjsGithub95** [comment]
谢谢，我后来无脑全换`\ref`了
