### ISSUE TITLE
"Undefined control sequence" error.

### ISSUE THREAD

**Issue by tellisahin** [nuaatug/nuaathesis#52]
Greetings, dear fellows! I downloaded the zip folder, and I think I followed all the instructions correctly. I installed required language packages as well. However, when I run build.bat to get nuaathesis.cls I receive the following error message:

.
.
.
(c:/texlive/2020/texmf-dist/tex/latex/newpx/t1npxtt.fd) (./nuaathesis.dtx
***************************
* Character table correct *
***************************
[1] (c:/texlive/2020/texmf-dist/tex/latex/newpx/ts1zpltlf.fd)
Overfull \hbox (18.50583pt too wide) in paragraph at lines 181--184
\TU/SimSun(0)/m/n/10.53937 器，|  安 装 \T1/zpltlf/m/n/10.53937 T[]X Live \TU/SimSu
n(0)/m/n/10.53937 的 以 下 \T1/zpltlf/m/n/10.53937 col-lec-tion\TU/SimSun(0)/m/n/1
0.53937 ：| []\T1/npxtt/m/n/10.53937 langchinese, latexextra, science, pictures,
 fontsextra\TU/SimSun(0)/m/n/10.53937 。|

LaTeX Warning: Reference `tab:contents' on page 2 undefined on input line 201.

[2]

LaTeX Warning: Reference `tab:required' on page 3 undefined on input line 221.

[3]
! Undefined control sequence.
l.274 % \sout
             {（因为想不出合适的英文翻译，所以就用拼音了）}
?

This can be fixed? OS is windows 10, and the system language is English.

**Comment by yzwduck** [comment]
Greetings from 2021 and thanks for reporting this issue.
It seems that the `\sout` is not defined, which should be provided by `ulem` package. For unknown reasons `nuaathesis.dtx` didn't include `ulem`, maybe some other package also provided this macro, until a recent update.
It's not hard to fix it. I'll update it this weekend.

PS: even the build fails, `nuaathesis.cls` should already be generated.

```
diff --git a/nuaathesis.dtx b/nuaathesis.dtx
index deb544b..cb5e564 100644
--- a/nuaathesis.dtx
+++ b/nuaathesis.dtx
@@ -2435,6 +2435,7 @@ and the derived files           nuaathesis.ins,
 \RequirePackage{hypdoc}
 \PassOptionsToPackage{no-math}{fontspec}
 \RequirePackage{amsmath}
+\RequirePackage{ulem}
 \RequirePackage[UTF8,scheme=chinese]{ctex}
 \RequirePackage{newpxtext}
 \RequirePackage{newpxmath}
```

**Comment by tellisahin** [comment]
It worked :) Thank you so much for your attention!
