### ISSUE TITLE
中文参考文献出现et al

### ISSUE THREAD

**Issue by HjsGithub95** [nuaatug/nuaathesis#54]
你好，我在检查论文的时候发现，中文参考文献出现多个作者的时候模板使用了"et al"而没有使用", 等"，请问这个要如何修改呢？

**Comment by weijiazong** [comment]
我也遇到相同的问题了，目前手动修改。。。

**Comment by HjsGithub95** [comment]
> 我也遇到相同的问题了，目前手动修改。。。

请问你是怎么修改的，我发现我没法手动加", 等"

**Comment by yzwduck** [comment]
Hi, 我试图复现这个问题，但是没能成功。
能否提供一份样例代码（bib 文件）以方便进一步调查？

**Comment by HjsGithub95** [comment]
我选了两个有这个问题的文献添加进了你们的参考文献示例中，编译出来也是这样的
[sample.zip](https://github.com/nuaatug/nuaathesis/files/5795839/sample.zip)


![QQ截图20210111205311](https://user-images.githubusercontent.com/44230268/104184890-2384fe00-544f-11eb-8d15-f602f1f5a5ec.png)

**Comment by yzwduck** [comment]
文献需要手工标记它的语言，如:
```
@article{5,
  title={无人直升机的姿态增强学习控制设计与验证},
  author={安航 and 鲜斌 and others},
  journal={控制理论与应用},
  volume={36},
  number={4},
  pages={516--524},
  year={2019},
  publisher={华南理工大学 中国科学院数学与系统科学研究院},
  lang = {zh}
}
```
这样编译的结果是:
```
安航, 鲜斌, 等. 无人直升机的姿态增强学习控制设计与验证 [J]. 控制理论与应用, 2019,
36(4):516–524.
```

**Comment by HjsGithub95** [comment]
o，这个还真没注意，谢谢
