### ISSUE TITLE
欢迎加入南航毕业论文 LaTeX 交流群！

### ISSUE THREAD

**Issue by cyzhou1221** [nuaatug/nuaathesis#58]
QQ 群号: 827139486

有什么问题大家一起讨论呀！

**Comment by yzwduck** [comment]
上一个 QQ 群已经 3 年没动静了。

**Comment by cyzhou1221** [comment]
> 上一个 QQ 群已经 3 年没动静了。
hhh，去年还有我认识的学长用过

**Comment by Triple-Z** [comment]
建议使用 GitHub Discussions，如：https://github.com/sjtug/SJTUThesis/discussions

**Comment by yzwduck** [comment]
> 建议使用 GitHub Discussions，如：https://github.com/sjtug/SJTUThesis/discussions

打开了 Discussions

**Comment by ThreeWaterGG** [comment]
> 群号没了..

**Comment by chenzetong** [comment]
> QQ 群号: 827139486
> 
> 有什么问题大家一起讨论呀！

搜索不到本群呀

**Comment by huhu312** [comment]
群搜不到呀

**Comment by yzwduck** [comment]
由于已经有两个 QQ 群消失了，我认为目前 IM 可能不适合用于讨论本模板的使用问题，暂且把 issue 关了。

如果遇到使用问题，欢迎在 [discussions](https://github.com/nuaatug/nuaathesis/discussions) 上发帖（可在 watch 里添加 discussions）。如不方便公开讨论，也可以发邮件（或者线下讨论，如果有必要的话）。
