### ISSUE TITLE
中文算法包的问题

### ISSUE THREAD

**Issue by QxGeng** [nuaatug/nuaathesis#70]
请问有中文的算法伪代码包吗？
算法标题Algorithm可以改为中文吗

**Comment by yzwduck** [comment]
我没查过是否存在中文的伪代码包。
标题 Algorithm 的汉化依赖于伪代码包的实现，通常是把某个宏进行重定义，如：
```latex
% 写在 begin{document} 前，比如 global.tex 里
\def\algorithmautorefname{算法}
\makeatletter
\renewcommand{\ALG@name}{算法}
\makeatother
```

**Comment by QxGeng** [comment]
> 我没查过是否存在中文的伪代码包。 标题 Algorithm 的汉化依赖于伪代码包的实现，通常是把某个宏进行重定义，如：
> 
> ```
> % 写在 begin{document} 前，比如 global.tex 里
> \def\algorithmautorefname{算法}
> \makeatletter
> \renewcommand{\ALG@name}{算法}
> \makeatother
> ```

好的 谢谢您
我初步按照下面的方法也改了格式
\floatname{algorithm}{算法}
\renewcommand{\algorithmicrequire}{\textbf{输入:}}
\renewcommand{\algorithmicensure}{\textbf{输出:}}
